server.port=${PORT:8086}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# MariaDB configuration.
spring.datasource.url = jdbc:mariadb://localhost:3306/vaadinstart
spring.datasource.username = root
spring.datasource.password =
spring.jpa.hibernate.ddl-auto = update
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,com.master,com.flowingcode
spring.jpa.defer-datasource-initialization = true
spring.sql.init.mode = always
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true