insert into application_user (version, id, username,name,hashedPassword,profilePicture,lang) values (1, '1','user','User','$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe','','en')
insert into User_roles (User_Id, roles) values ('1', 'USER')
insert into application_user (version, id, username,name,hashedPassword,profilePicture,lang) values (1, '2','admin','Admin','$2a$10$jpLNVNeA7Ar/ZQ2DKbKCm.MuT2ESe.Qop96jipKMq7RaUgCoQedV.','','en')
insert into User_roles (User_Id, roles) values ('2', 'USER')
insert into User_roles (User_Id, roles) values ('2', 'ADMIN')
